apiVersion: v1
kind: Service
metadata:
  name: lb-unifi
  namespace: reverse-proxy
  labels:
    app: lb-unifi-app-pod
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 8443
  selector:
    app: unifi-app-pod
  loadBalancerIP: 192.168.88.199
